### PR TITLE
Xiasenwang

### PR DESCRIPTION
**Pull request by Jason64178**

### CODE REVIEW

**Comment by zhehe0408** [comment]
Background: Deal with the date information of the raw data.
The code works well, easy to reuse.
Readability of the code: good
Python packages: pandas urllib2 
More comments will be better.

**Comment by Jason64178** [comment]
I add more comments on my codes in my codes.

**Comment by Jason64178** [comment]
I added more comments in the codes.

**Comment by gengho** [comment]
Hw 7 writen by Zhe He:
Background

Describe what the application does
This script load the car2go raw data and map data and count the records by depart and destination.
Describe the role of the code being reviewed
Road the raw file and produce the core data.
Comment on

Choice of variable and function names
Easy to read.

Readability of the code
Good.

How improve reuse and efficiency

How use existing python packages
pandas
matplotlib
numpy

**Comment by xycyx** [comment]
This script can send the request to a URL and then save the data every 30 s.
Using urllib2 to access the Internet resources. 
The overall idea and achieve is clear. 
More comments could be better.
Besides, could it be packaged as a more generally tool?

**Pull request merged**
