### PR TITLE
Yuxuan Cheng hw7

### PR DESCRIPTION
**Pull request by xycyx**

### CODE REVIEW

**Comment by zhehe0408** [comment]
The code runs well, helping us to read the shapefiles in ArcGIS.
The comments explain the background and purpose clearly.
Choice of variable and function names: Easy to read.
Readability of the code: Good.
Too many blank lines.

**Comment by Jason64178** [comment]
This file draws the census blocks in Seattle.
It also draws the heat map of all the block.

The choice of Choice of variable and function names is good.
Comments made the codes more readable.
The improvement may not be needed.
existing python packages: shapely, geopandas, pandas, numpy, matplotlib, seaborn, pysal and scipy

**Comment by xycyx** [comment]
Thanks for your kind suggestions, I've updated my script based on your advice.

**Comment by xycyx** [comment]
Deleted the useless blank lines and add more useful comments and supporting materials. 
Removed the heat map part to an independent part.

**Pull request merged**
